feat: add optional `deleted` field to common (proto and schema)
digidem/mapeo-schema pull request #138
Opened 2023-08-24 14:39 UTC by tomasciccola

this would close #84

2023-09-25 14:50 UTC, tomasciccola commented
I'm wondering how to test an invalid value for the `deleted` field. On the JSONSchema level we can force `deleted` to be true but I don't know a way to do it on the protobuf level (maybe with an `option` ??) @gmaclennan

2023-09-26 16:02 UTC, gmaclennan requested changes
I suggest we make `deleted` required, it will make all the code easier I think.

2023-09-26 17:09 UTC, gmaclennan requested changes
For completeness sake there should be a test for when deleted = `true`

2023-09-27 13:53 UTC, gmaclennan approved these changes

2023-09-27 14:20 UTC, merged