Feat: two icon types (svg and png)
digidem/mapeo-schema pull request #174
Opened 2024-02-22 16:01 UTC by tomasciccola

This should close #160

2024-03-04 20:11 UTC, EvanHahn requested changes

2024-03-04 20:11 UTC, EvanHahn commented on proto/icon/v1.proto
> +    message BlobVersionId {
It seems like both SVGs and PNGs use `BlobVersionId` and `Size`. Maybe we could move those out?

2024-03-04 20:11 UTC, EvanHahn commented on proto/icon/v1.proto
> +    BlobVersionId blobVersionId = 3 [(required) = true];
Should this be `2` instead of `3`?

```suggestion
    BlobVersionId blobVersionId = 2 [(required) = true];
```

2024-03-04 20:11 UTC, EvanHahn commented on proto/icon/v1.proto
> +  message IconVariant {
Maybe this message could have `Size` and `BlobVersionId` on it?

2024-03-07 03:08 UTC, EvanHahn requested changes

2024-03-07 15:14 UTC, tomasciccola commented on src/lib/decode-conversions.ts
> +  }
Its seems that ts doesn't grab the type guard  (is it called like that?) when moving that check onto `convertIconVariant`, complaining that `blobVersionId` could be undefined

2024-03-07 15:16 UTC, tomasciccola commented on src/lib/encode-conversions.ts
> +    } else {
It seems that, according to ts, adding that additional check doesn't make sense (`property 'mimeType' doesn't exist on type 'never'`)

2024-03-07 15:23 UTC, tomasciccola commented on src/lib/encode-conversions.ts
hehe, yeah. I forgot to push that and the unused imports...

2024-03-07 15:28 UTC, tomasciccola commented on src/lib/encode-conversions.ts
> +    } else {
I correct myself, I can add that additional check but I can't print the unsupported mimeType itself (that was what ts was complaining about...)

2024-03-11 15:19 UTC, EvanHahn commented on src/lib/encode-conversions.ts
> +    } else {
I think we can do exhaustiveness checks a little better across this repo. Opened #175 which does this; intended to be merged into this PR (or done afterward if you want).

2024-03-11 15:19 UTC, EvanHahn approved these changes

2024-03-11 20:34 UTC, EvanHahn approved these changes

2024-03-11 21:18 UTC, merged