feat!: replace `createdBy` with `originalVersionId`
digidem/mapeo-schema pull request #191
Opened 2024-07-10 19:54 UTC by EvanHahn

See <https://github.com/digidem/mapeo-core-next/issues/371> for details.

2024-07-11 21:45 UTC, gmaclennan requested changes
Thanks for this. I think we should encode this like we do the versionIds for Links. Also some questions about the typing of docs with originalVersionId and making sure we're not loosing type safety, particularly on writes.

2024-07-11 21:45 UTC, gmaclennan commented on proto/common/v1.proto
> +  optional string originalVersionId = 5;
This should be the same type as `Link`:

```
message Link {
    bytes coreDiscoveryKey = 1;
    int32 index = 2;
  }
```

Maybe rename `Link -> VersionId`

2024-07-11 21:45 UTC, gmaclennan commented on schema/common/v1.json
> +    "originalVersionId",
This does get confusing, because is this required or not? It seems from https://github.com/digidem/mapeo-core-next/pull/715 that we are not storing this on creation, so reads will not include this/

Trying to fully represent the type in JSONSchema might be difficult, it might be easier to do in the TypeScript defs in this repo, maybe something like:

```ts
type CommonNew = (Omit<Common, 'links' | 'originalVersionId'> & { links: [] }) | SetRequired<Common, 'originalVersionId'>
```

e.g. you originalVersionId can be missing if link is an empty array, but otherwise it is required.

2024-07-11 21:45 UTC, gmaclennan commented on src/encode.ts
> +  mapeoDoc: OmitUnion<MapeoDocInternal, 'versionId' | 'originalVersionId'>
I think it's optional rather than omitted?

2024-07-11 21:45 UTC, gmaclennan commented on src/lib/decode-conversions.ts
> +
Ah, I see re. my comment above about it being required in JSON Schema is maybe ok given you are always appending it here.

2024-07-11 21:45 UTC, gmaclennan commented on src/lib/decode-conversions.ts
> +
But maybe the encode function could benefit from the stricter typing and this same check when writing.

2024-07-11 21:45 UTC, gmaclennan commented on src/lib/encode-conversions.ts
> +    OmitUnion<MapeoDocInternal, 'versionId' | 'originalVersionId'>,
I think we're loosing some type safety where you are doing this, but it's late so maybe I'm missing something?

2024-08-15 14:48 UTC, EvanHahn commented on proto/common/v1.proto
> +  optional string originalVersionId = 5;
Done in e3024bea0987037111ec38bf2d1787d3a8972775.

2024-08-15 14:48 UTC, EvanHahn commented on src/encode.ts
> +  mapeoDoc: OmitUnion<MapeoDocInternal, 'versionId' | 'originalVersionId'>
Done in d1b0975b5e2cf8f2beee6a1a2ad5fcc6fd251a92.

2024-08-15 14:48 UTC, EvanHahn commented on src/lib/decode-conversions.ts
> +
I _think_ I addressed this in d1b0975b5e2cf8f2beee6a1a2ad5fcc6fd251a92.

2024-08-15 14:48 UTC, EvanHahn commented on src/lib/encode-conversions.ts
> +    OmitUnion<MapeoDocInternal, 'versionId' | 'originalVersionId'>,
I think I did this in d1b0975b5e2cf8f2beee6a1a2ad5fcc6fd251a92, but maybe you were imagining something else.

2024-08-23 08:40 UTC, gmaclennan approved these changes
This looks good to merge.

2024-08-24 15:47 UTC, merged