feat: add `configName` and `configVersion` to `projectSettings`
digidem/mapeo-schema pull request #197
Opened 2024-07-22 19:58 UTC by tomasciccola

This should move forward exposing config metadata to the frontend. 
Part of https://github.com/digidem/comapeo-mobile/issues/527

2024-07-23 14:15 UTC, EvanHahn requested changes
One question about whether `configVersion` should be an integer instead...not sure.

2024-07-23 14:15 UTC, EvanHahn commented on proto/projectSettings/v1.proto
> +  string configVersion = 7;
I think this is fine but I wonder if a simple integer would be simpler for users? Two reasons:

1. Semver is probably a little harder for users to understand
2. A `string` could contain garbage data

```suggestion
  uint32 configVersion = 7;
```

2024-07-23 15:05 UTC, tomasciccola commented on proto/projectSettings/v1.proto
> +  string configVersion = 7;
I agree, but maybe should loop in @gmaclennan  since he's thinking about semversioning configs (see https://github.com/digidem/comapeo-mobile/issues/527)

2024-07-25 13:48 UTC, tomasciccola commented on proto/projectSettings/v1.proto
> +  string configVersion = 7;
An issue that comes with this is: 
`configVersion` comes from the `version` field on the `package.json` which is usually a string; we could:
* find another way of denoting version of a config
* having some mechanism to enforce that the 'version' field is a valid int (maybe on build time of a config)
* keeping it as a string and be prepared to catch possible garbage
* some other that I haven't thought of

I don't favor anyone (maybe more inclined to second option?).

2024-07-25 13:51 UTC, tomasciccola commented on proto/projectSettings/v1.proto
> +  string configVersion = 7;
Also wondering about version in the context of a non-technical person. Does an arbitrary number convey that meaning? Wouldn't a date be a more universal way of expressing versioning (so basically, expressing when this config was built?)

2024-07-29 16:59 UTC, gmaclennan commented
Following up here from our call about this today. Proposal is to have these fields:

- `configName: string`: human readable name for the config, defined by the person who creates the config.
- `configBuildDate: string`: ISO date of when the config was built. Should encode to proto as a timestamp, like we do for other ISO date fields.
- `configVersion: string`: We discussed the merits of having a semver version name, but decided to not use it for now due to the challenges for the person creating the config to know how to increment the version. We discussed keeping it for future use, but on reflection I suggest we drop it from the schema for now, and add it if needed later. I've been burned by adding things to the schema that we don't actually use in the past.

Separately, I think it's worth capturing some additional metadata when a config is imported:

- `configImportDate` - the date the config was actually imported into the project, different to the build date.
- `configFileName` - the name of the file that the config was imported from.
- `configFileVersion` - the config file format version

I think this data could be useful for debugging and we could expose it to the user in the future, and at least include it in debug info.

With all this data I think maybe put it all under a property, e.g. `configMetadata`? I realize that's jjust me being OCD about organization...

2024-07-29 17:06 UTC, tomasciccola commented
> Following up here from our call about this today. Proposal is to have these fields:

>     * `configVersion: string`: We discussed the merits of having a semver version name, but decided to not use it for now due to the challenges for the person creating the config to know how to increment the version. We discussed keeping it for future use, but on reflection I suggest we drop it from the schema for now, and add it if needed later. I've been burned by adding things to the schema that we don't actually use in the past.

I agree about this and was in fact not adding `configVersion` on the schema. `metadata.json` on config files will still save the `configVersion`, we can just ignore it for now
> 
> 
> Separately, I think it's worth capturing some additional metadata when a config is imported:


>     * `configImportDate` - the date the config was actually imported into the project, different to the build date.
Ok, I'll add that field

>     * `configFileName` - the name of the file that the config was imported from.

Not that sure about the utility of this since we are already adding name, but don't have anny issues with adding it
> 
>     * `configFileVersion` - the config file format version

I'm adding this as an int32. And then in `mapeo-core-next` we could have a `SUPPORTED_CONFIG_VERSIONS = [1,2..]` so that we can check if we're importing a config format we support. Do you think this is enough, or should we set it as a string and use semver? I think the complexities of parsing a semver string may not be worth it, but we can discuss it further...


> With all this data I think maybe put it all under a property, e.g. `configMetadata`? I realize that's jjust me being OCD about organization...

heh, I'm actually doing this (nesting everything under `configMetadata`.

On the other hand, I'm making `configMetadata` and its fields optional since a user may create a project (which means calling `setProjectSettings`) before importing a config.

2024-07-29 20:06 UTC, EvanHahn approved these changes

2024-07-29 20:06 UTC, EvanHahn commented on proto/projectSettings/v1.proto
> +    optional int32 fileVersion = 4;
Nit: if the minimum value is `0`, this should be an `uint32`.

```suggestion
    optional uint32 fileVersion = 4;
```

2024-07-30 08:28 UTC, gmaclennan commented
> I'm adding this as an int32. And then in `mapeo-core-next` we could have a `SUPPORTED_CONFIG_VERSIONS = [1,2..]` so that we can check if we're importing a config format we support. Do you think this is enough, or should we set it as a string and use semver? I think the complexities of parsing a semver string may not be worth it, but we can discuss it further...

This doesn't support the case of forwards-compatibility. E.g. the version of comapeo we release today needs to know which future versions of the file format it is able to parse. I suggest we use [comver](https://gitlab.com/staltz/comver) for the file format (`MAJOR.MINOR`). The value stored in this field will not be parsed (it's just there to support debugging in the future), but for the file reader we should attempt to parse this and throw if it can't be parsed e.g.

```js
function parseVersion(version) {
    const regex = /^(\d+)\.(\d+)$/;
    const match = version.match(regex);

    if (!match) {
        throw new Error('Invalid file version: ' + version);
    }

    const major = parseInt(match[1], 10);
    const minor = parseInt(match[2], 10);

    if (major > SUPPORTED_VERSION) {
        throw new Error('Invalid version: MAJOR cannot be greater than ' + SUPPORTED_VERSION);
    }

    return {
        major: major,
        minor: minor
    };
}
```

2024-07-30 08:33 UTC, gmaclennan requested changes

2024-07-30 08:33 UTC, gmaclennan commented on proto/projectSettings/v1.proto
> +    optional int32 fileVersion = 4;
I think we should make all of these field required. It will make front-end code easier. The file format can ensure they are required, so we know they will always exist if the configMetadata property exists.

2024-07-30 13:35 UTC, tomasciccola commented on proto/projectSettings/v1.proto
> +    optional int32 fileVersion = 4;
Added on last commit. timestamps will map to `string | undefined` so I had to add a check in the `decode-conversions` code which I _think_ makes sense

2024-07-30 13:48 UTC, tomasciccola commented
> This doesn't support the case of forwards-compatibility. E.g. the version of comapeo we release today needs to know which future versions of the file format it is able to parse. I suggest we use [comver](https://gitlab.com/staltz/comver) for the file format (`MAJOR.MINOR`). The value stored in this field will not be parsed (it's just there to support debugging in the future), but for the file reader we should attempt to parse this and throw if it can't be parsed e.g.

Ok. So `fileVersion` would be a string (and we can add a regex on the JSONSChema to validate the field when encoding). 
That validation pseudo-code you pasted would live on the `config-import` in `mapeo-core-next` right?

2024-07-30 14:24 UTC, gmaclennan commented
> Ok. So `fileVersion` would be a string (and we can add a regex on the JSONSChema to validate the field when encoding).

Yes, although I don't think regex in JSONSchema is necessary - this field will never be parsed by anything, it's just for info, so can be just left as an opaque string.

> That validation pseudo-code you pasted would live on the `config-import` in `mapeo-core-next` right?

Yes. The version name read from the config file does need to be parsable and conform to MAJOR.MINOR

2024-07-30 14:26 UTC, gmaclennan commented on proto/projectSettings/v1.proto
> +    string fileVersion = 4;
Storing this info in the project settings is just for debug purposes - it will not need to be parsed. I think there is no need for the schema to be opinionated about it.

2024-07-30 14:27 UTC, gmaclennan commented on src/lib/decode-conversions.ts
> +    throw new Error('Missing required property configMetadata')
This shouldn't be a required prop - a project could be created without any config imported yet.

2024-07-30 15:03 UTC, tomasciccola commented on src/lib/decode-conversions.ts
> +  return configMetadata as ProjectSettings['configMetadata']
This checks are because `dates` in protobuf always generate types with `| undefined` but the rest of the fields are mandatory; so if we don't have type errors then we have the guarantee that when decoding, if `configMetadata` exists, then all fields _should_ be there. 
When encoding this shouldn't be an issue because types for JSON doesn't have this problems: if you set a date as required it won't be '| undefined'.
So in a sense, those checks only exist to please typescript

2024-07-30 15:04 UTC, tomasciccola commented on proto/projectSettings/v1.proto
> +  optional ConfigMetadata configMetadata = 3;
Fixed on last couple of commits

2024-07-30 21:54 UTC, gmaclennan reviewed
This has all left me confused about how we handle required/optional fields in protobuf. ts-proto gives the impression that primitives are "required", because the type is never `undefined`, but it actually decodes to defaults for primitives, like an empty string. I can't quite get my head around what we should do, maybe we could check in about this tomorrow?

2024-07-30 21:54 UTC, gmaclennan commented on src/lib/decode-conversions.ts
> +  return configMetadata as ProjectSettings['configMetadata']
Not exactly mandatory. If `name` and `fileVersion` are missing from the protobuf, then they will be decoded as empty strings. The whole world of optional fields in protobuf is super confusing, including how they are decoded by ts-proto (see docs), but there are no easy solutions - it's a feature of protobuf that required fields are not supported. I'm not entirely sure what we should do - maybe we should leave everything optional and leave the API consumer to decide what to do with it if fields are missing, rather than throwing during decode?

2024-07-31 12:44 UTC, tomasciccola commented
> This has all left me confused about how we handle required/optional fields in protobuf. ts-proto gives the impression that primitives are "required", because the type is never `undefined`, but it actually decodes to defaults for primitives, like an empty string. I can't quite get my head around what we should do, maybe we could check in about this tomorrow?

Same, I thought I already knew were to deal with optionals but this threw me off. Same happened in #199. Basically every non-primitive type seems to be optional which is a drag. Basically I internally think about all this checks as "This should be impossible to happen but we need to please typescript" (but maybe is not impossible to happen?)

2024-07-31 17:01 UTC, EvanHahn approved these changes

2024-07-31 17:01 UTC, EvanHahn commented on test/fixtures/good-docs-completed.js
> +      },
Should this also have a config version?

2024-07-31 17:19 UTC, tomasciccola commented on test/fixtures/good-docs-completed.js
> +      },
MHM, I mean, since we're not using the `configVersion` from metadata.json (for now) I didn't added to the schema. We can added later, but since we allow extra fields on the `metadataFile` (see the core-next PR) I see no issue with this. 
Just to clarify `configVersion` is the version of the built config, and `fileVersion` is the config format file version. But maybe `fileVersion` is not clear enough as a name??

2024-07-31 18:18 UTC, EvanHahn approved these changes
LGTM!

I think we can now merge without Gregor's approval.

2024-07-31 18:58 UTC, merged