feat: standarize refs accross all docs
digidem/mapeo-schema pull request #199
Opened 2024-07-25 15:41 UTC by tomasciccola

So, I tried to standarize references in docs by creating a `ref` protobuf and importing it in every document that needs it. 
For protobufs is useful that we can import, which I'm not doing in JSONSchema (I'm basically copy-pasting `ref` on documents that use it, changing only the description). This can became _kinda_ hard to track (but not a huge issue). I know JSONSchema allows to reference other schemas but I know that we're not using that feature for i.e. `Common` so there's probably a shortcoming I'm forgetting about.
Besides `docId` and `versionId` I added `type` so that we can track which type of documents are referenced. This was already used in tracks and translations (through `schemaRef`, now removed). Regarding this, I think it may make sense to have runtime checks (i.e. tracks should only reference observations) instead of having different `ref` types which only differ on the type of doc they reference

2024-07-25 15:42 UTC, EvanHahn commented
I'll review this soon. Could you fix the merge conflicts before I do?

2024-07-25 15:51 UTC, tomasciccola commented
Regarding asserting correct reference types:
1. Tracks should only reference observations
2. Presets should only reference fields or icons
3. Translations? (On the top of my head we translate fields and presets, but maybe we want to keep it lean?)

Maybe this is smth we don't need to do and we can be lean about it...

2024-07-29 16:50 UTC, gmaclennan reviewed
Some initial feedback/thoughts on a quick read-through:

- A `versionId` is not a hex encoded string. We already have a proto def for this called [`Link`](https://github.com/digidem/mapeo-schema/blob/02a723576372313e102dad3ff45563efb7dbab05/proto/common/v1.proto#L10). We [encode it and decode it](https://github.com/digidem/mapeo-schema/blob/main/src/lib/utils.ts#L41-L60) by hex-encoding the discovery key and joining with `/` and the index.
- Also change `Link` to use the same definition.
- I think we should have a `ref` definition that does not include a `type`, with the type implicit. Otherwise we are allowing for invalid refs. E.g. a preset can have a `fieldRefs` field, which can only be refs to fields, and don't need a `type`. Right now the only place I think where we need a `type` for refs is for translations. Since it's not an array, maybe we can just keep it as a separate `refType` field? I'm not sure about this one and would welcome Evan's thoughts.
- Where possible, we should avoid calling this field `ref` or `refs`, and include a more descriptive name like `fieldRefs`, to make it easier to understand.
- For tracks, I think it's maybe ok to just say the refs are `observationRefs`. I think if we want to link other things to a track, we can do it as a separate field.

2024-07-29 18:19 UTC, EvanHahn requested changes
> I think we should have a `ref` definition that does not include a `type`, with the type implicit. Otherwise we are allowing for invalid refs. E.g. a preset can have a `fieldRefs` field, which can only be refs to fields, and don't need a `type`. Right now the only place I think where we need a `type` for refs is for translations. Since it's not an array, maybe we can just keep it as a separate `refType` field? I'm not sure about this one and would welcome Evan's thoughts.

I agree with this. I think it makes more sense to have two fields: `fieldRefs` and `iconRefs`, or `observationRefs`.

That probably means removing `RefType` from `proto/ref/v1.proto`.

2024-07-29 18:19 UTC, EvanHahn commented on proto/translation/v1.proto
> +  string fieldRef = 3;
Should this be a `Ref_1`?

2024-07-30 18:16 UTC, tomasciccola commented
Following the feedback I:
* Add a `VersionId` proto to be used in `Common.links` and other refs
* Delete `Ref_1` proto
* Add specific `ref` messages to the corresponding protos (and schemas):
  1. `fieldRefs` and `iconRef` on presets
  2. `observationRefs` on tracks
  3. `docRef` on translation
* Add checks for undefined fields. This mostly happens when we have a list of refs (repeated) where, for some reason that I don't know, `versionId` can be `undefined`. Types are generated like that and from what I can see non-primitives in protobufs generate types with `| undefined`
* Fix types and tests
* I took de liberty of renaming `fieldRef` to `propertyRef` in translation since `fieldRef` can be misleading (its not related to `Field` whatsoever). `propertyRef` seemed more apt since its actually a 'dotprop' string. I can rollback that change if y'all feel like it

2024-07-31 16:58 UTC, EvanHahn requested changes
LGTM other than a few questions on tests.

2024-07-31 16:58 UTC, EvanHahn commented on test/fixtures/bad-docs.js
> +    text: 'preset that references an invalid docTypr',
Nitpick:

```suggestion
    text: 'preset that references an invalid docType',
```

2024-07-31 16:58 UTC, EvanHahn commented on test/fixtures/bad-docs.js
> +    text: 'track ref type can only refer to observations',
When is this possible?

2024-07-31 16:58 UTC, EvanHahn commented on test/fixtures/bad-docs.js
> +      refs: [
Is this possible?

2024-07-31 16:58 UTC, EvanHahn commented on test/fixtures/bad-docs.js
> +      refs: [
Is this possible?

2024-07-31 17:46 UTC, tomasciccola commented
> LGTM other than a few questions on tests.

Thanks for catching this. It was left from when `Ref` was the same across every docType and with a type field. 
Now it doesn't make sense to keep it

2024-07-31 17:58 UTC, merged