Convertion functions for authStore types
digidem/mapeo-schema pull request #96
Opened 2023-08-02 14:59 UTC by tomasciccola

Things to consider:
* what fields are required? 
  * Role: every field
* action name delimiters:
  protobuf doesn't allow colons (':') on identifiers, so to avoid type problems I basically replaced that delimiter with underscore ('_'). So in schemas `role:set` becomes `role_set`. Another separator could be chosen, or a convertion function (convertAction) could be written; I've tried but failed with that

2023-08-02 16:41 UTC, gmaclennan requested changes
Looks good to me, I think the enums with `_` are fine.

I think the JSONSchema for Role should include `UNRECOGNIZED` as an enum option, rather than trying to use a default, and the client should handle that accordingly. This is for future compatibility so that a new action does not break existing clients.

Needs changes from master merged in, for the const: schemaName change.

2023-08-02 18:37 UTC, tomasciccola commented
> Looks good to me, I think the enums with `_` are fine.
> 
> I think the JSONSchema for Role should include `UNRECOGNIZED` as an enum option, rather than trying to use a default, and the client should handle that accordingly. This is for future compatibility so that a new action does not break existing clients.
> 
> Needs changes from master merged in, for the const: schemaName change.

Ok, I see that, for example, the `Field` schema doesn't have an `UNRECOGNIZED` option on the `type` field (only `text|number|selectOne|selectMultiple`) in what sense that case is different? mostly because we're certain we are not going to add additional options in the future??

2023-08-03 14:14 UTC, gmaclennan commented
> Ok, I see that, for example, the `Field` schema doesn't have an `UNRECOGNIZED` option on the `type` field (only `text|number|selectOne|selectMultiple`) in what sense that case is different? mostly because we're certain we are not going to add additional options in the future??

Ah good point. I initially had initially thought that a `text` field is a good fallback for anything, but because the actual values stored in the tags could be different, I think it's better for the client to decide how to deal with this, by which I mean that `UNRECOGNIZED` is a good option here - if the client sees that, it can look at any existing value and choose the best way to display it.

It's a different case with the `appearance` option, where `multiline` is a good fallback for any future options.

2023-08-03 14:16 UTC, gmaclennan approved these changes

2023-08-03 20:34 UTC, merged